--Not used as the data is now generated by the application
INSERT INTO Run (id, title, started_on, completed_on, miles, location)
VALUES (1, 'Morning Run', '2025-01-14 14:55:14' ,'2025-01-14 15:55:14', 10, 'INDOOR');